gui:
  theme:
    activeBorderColor:
      - green
      - bold
    inactiveBorderColor:
      - white
    selectedLineBgColor:
      - blue
  showIcons: true
  mouseEvents: true

os:
  editPreset: helix
